version: '3'

services:
  jekyll:
    build:
      context: ./
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/usr/src/app
    command: bundle exec jekyll serve -H 0.0.0.0 --livereload